rules:
  no-misspelled-properties: 2
  no-invalid-hex: 2
  no-color-literals: 2
  no-qualifying-elements: 2
  no-url-domains: 2
  no-transition-all: 2
  no-duplicate-properties:
  - 2
  -
    exclude:
      - display
      - clip
  class-name-format:
  - 1
  -
    ignore:
      - gsc-control-cse-pt_PT
      - gs-webResult
  no-vendor-prefixes:
  - 1
  -
    excluded-identifiers:
      - webkit
      - moz
  brace-style:
  - 1
  -
    style: stroustrup
  mixins-before-declarations:
  - 1
  -
    exclude: ['media-query']
  force-pseudo-nesting: 0
  property-sort-order:
    - 1
    -
      order:
        - @include
        - display
        - -webkit-align-items
        - align-items
        - -webkit-flex-wrap
        - flex-wrap
        - -webkit-flex-shrink
        - flex-shrink
        - -webkit-justify-content
        - justify-content
        - position
        - bottom
        - left
        - right
        - top
        - float
        - z-index
        - height
        - max-height
        - min-height
        - max-width
        - min-width
        - width
        - border
        - border-color
        - border-top
        - border-radius
        - margin
        - padding
        - padding-right
        - font
        - font-family
        - font-size
        - color
        - text-align
        - text-decoration
        - text-shadow
        - text-transform
  force-element-nesting: 0
  no-ids: 0
  property-sort-order: 0
