rules:
  no-misspelled-properties: 2
  no-color-literals: 2
  no-qualifying-elements: 2
  class-name-format:
  - 1
  -
    ignore:
      - gsc-control-cse-pt_PT
      - gs-webResult
  no-duplicate-properties:
  - 1
  -
    exclude:
      - display
      - clip
  no-vendor-prefixes:
  - 1
  -
    excluded-identifiers:
      - webkit
      - moz
  mixins-before-declarations: 0
  force-pseudo-nesting: 0
  brace-style:
  - 1
  -
    style: stroustrup
  property-sort-order: 0
  force-element-nesting: 0
  no-ids: 0
