#
#
# WARNING: THIS FILE IS REPLACED BY ANOTHER VERSION IN PRODUCTION.
#
# IF YOU ARE MAKING CHANGES TO THIS FILE THAT ARE INTENDED TO BE REFLECTED IN PRODUCTION,
# MAKE SURE YOU ALSO CHANGE THE VERSION USED THERE.
# PRODUCTION'S CONFIGURATION FILE CAN BE FOUND ON THIS GITHUB REPO: https://github.com/brasil-de-fato/puppet
# UNDER modules/frida/files/site/_config.yml
#

#
#
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
language: pt-br
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: brasildefato.com.br
root: /
baseurl: '/'
permalink: :url

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: main

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:brasil-de-fato/site.git
  branch: gh-pages
